language: ruby
addons:
  code_climate:
    repo_token:
      secure: ZAE4QQevFCrERFy5R/G9NV7uQeO8mdyFiVIs7e4sLrNnVdKX2Gj/oR8LN7gKlkh07o9AUMpZLDJx/qJs4uZZ0qWHzOCDNgibnfqZ/ncXsIg/uEu+TlpZxYlAaJg2+94lPmT8VF2GpyKCMTzzY67UMq9n0R0CfSxEr4alh3uJmorvwPuIZIzr0dNpnjtIVg4c+anytTa9gxjcjffHWMU6xdtQZKj2J47UjxKbn2ide0UfBoupTqY//s9dsZRU+cCwCPI3AU5R6yIM3splkZGgYZjp/sl3Os6iLEDsKwfPBQzUVmf5hjCPqXW+2K+lA/ufD4YVyBERNvNH2K6+4RebNnR19A6o4kqcHrlbRle38KyBjFOBhBE1kwT8+TzGUinYIY2/QkhNDNHdN7CggWhRu6olHInmM5g+SdjPFAwmTpugv0Evy7Y8d0rCeTK7Ory1mN1ImjjusaUCN6lAxO+QbehqS/A2T1vPBsAjQ/zg9OX6zHp36KLqeiOKhEA9PSL8ruHWmmwUyqbmg2LE5SBfnYQ8UpaHA37FWNBng4NrrEO49foH/73daGiy4zutErxZoFPwdKAmjIfMo1mYyeCSqGlCPbqFgOBMlyamudLWUPSX+NLI0Woad/8xlY0/sbD2kcEhNvvJ/9v8vAozUExzfOJ4iJjYx8xLS1AlUYWyvAI=
after_success:
- bundle exec codeclimate-test-reporter
